// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKcn4zvanLOk-KyquTSiV9_IPURLydQQ4',
    appId: '1:926125069301:web:b69c721254cc8af34f46bc',
    messagingSenderId: '926125069301',
    projectId: 'ssredentore-65ea2',
    authDomain: 'ssredentore-65ea2.firebaseapp.com',
    storageBucket: 'ssredentore-65ea2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr1p9K6QeNyLqWSffiEuxSVcnK6K8uuBE',
    appId: '1:926125069301:android:94dbf7ef09754b624f46bc',
    messagingSenderId: '926125069301',
    projectId: 'ssredentore-65ea2',
    storageBucket: 'ssredentore-65ea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCatP8kAC8nczg9h5UMgdw75nYHbGSXfi8',
    appId: '1:926125069301:ios:b2e93a04b016d4364f46bc',
    messagingSenderId: '926125069301',
    projectId: 'ssredentore-65ea2',
    storageBucket: 'ssredentore-65ea2.appspot.com',
    iosBundleId: 'com.example.ssredentore',
  );
}
